# Generated by Django 6.0.6 on 2026-06-28 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.contestant')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'contestant'], name='voting_vote_poll_id_c6ded8_idx'), models.Index(fields=['voter'], name='voting_vote_voter_i_a33aec_idx'), models.Index(fields=['payment_ref'], name='voting_vote_payment_56f016_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoteAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('action', models.CharField(choices=[('vote_attempt', 'Vote Attempt'), ('vote_success', 'Vote Success'), ('vote_blocked', 'Vote Blocked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'action'], name='voting_vote_poll_id_a89039_idx'), models.Index(fields=['ip_address'], name='voting_vote_ip_addr_613d82_idx')],
            },
        ),
    ]
