# Generated by Django 6.0.6 on 2026-06-28 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('organizer', models.CharField(blank=True, help_text='Display name of the organizer. Defaults to creator.name on save.', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='polls/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ending_soon', 'Ending Soon'), ('closed', 'Closed'), ('draft', 'Draft'), ('new', 'New')], db_index=True, default='new', max_length=20)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price_per_vote', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='The user who created this poll.', on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contestants/')),
                ('votes', models.PositiveIntegerField(default=0, help_text='Denormalized vote count. Updated atomically via F() on each vote.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='polls.poll')),
            ],
            options={
                'ordering': ['-votes'],
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['slug'], name='polls_poll_slug_3e2bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status'], name='polls_poll_status_b99f43_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['category'], name='polls_poll_categor_1cd734_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['creator'], name='polls_poll_creator_4c4934_idx'),
        ),
        migrations.AddIndex(
            model_name='contestant',
            index=models.Index(fields=['poll'], name='polls_conte_poll_id_c8c0bd_idx'),
        ),
    ]
